phone/urls.py
from django.urls import path
from phone import views

app_name = "phone"
urlpatterns = [
    path("", views.index, name="index"),
    path('phones/', views.PhoneListView.as_view(), name='phone-list'),
    path('add-phone/', views.add_phone, name='add-phone'),
    path('get-report/', views.get_report, name='get-report')
]

phone_registration/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("phone.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

phone/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Create your models here.


class PhoneBrand(models.Model):
    name = models.CharField(max_length=50)
    nationality = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name} - {self.nationality}"

    class Meta:
        unique_together = ("name", "nationality")
        ordering = ['name']


class PhoneModel(models.Model):
    brand = models.ForeignKey(PhoneBrand, on_delete=models.CASCADE,
                              related_name='phone_model')
    model = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.brand.name} - {self.model} - {self.brand.nationality}"

    class Meta:
        unique_together = ("brand", "model")
        ordering = ['model']


class Phone(models.Model):
    phone_name = models.ForeignKey(PhoneModel, on_delete=models.CASCADE, related_name='phone')
    price = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10000)],
        help_text="The currency is the dollar"
    )
    color = models.CharField(max_length=100)
    screen_size = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(20.0)],
        help_text="Screen size in inches"
    )
    is_available = models.BooleanField(default=False)
    manufacturing_country = models.CharField(max_length=100)

    def __str__(self):
        return self.phone_name.model

    class Meta:
        unique_together = (
            'phone_name', 'price', 'color', 'screen_size', 'manufacturing_country'
        )
        ordering = ['-price']

phone/forms.py
from django.forms import ModelForm

from phone.models import Phone
from django import forms


class PhoneForm(ModelForm):
    class Meta:
        model = Phone
        fields = '__all__'

    def clean(self):
        cleaned_data = super(PhoneForm, self).clean()
        return cleaned_data


class BrandForm(forms.Form):
    brand = forms.CharField(max_length=100, label='Phone Brand')

phone/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.db import models
from phone.models import Phone, PhoneBrand
from phone.forms import PhoneForm, BrandForm

# Create your views here.


def index(request):
    return render(request, "index.html")


class PhoneListView(ListView):
    model = Phone
    template_name = 'phone/list.html'  # Specify your template name
    context_object_name = 'phones'  # Name of the context variable to use in the template


def add_phone(request):
    if request.method == "POST":
        form = PhoneForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('phone:phone-list')
    else:
        form = PhoneForm()

    context = {
        'form': form
    }

    return render(
        request, 'phone/add.html', context
    )


def get_report(request):
    if request.method == "POST":
        form = BrandForm(request.POST)
        if form.is_valid():
            brand = form.cleaned_data['brand']
            phones = Phone.objects.filter(
                phone_name__brand__name__iexact=brand
            )
    else:
        phones = None
        form = BrandForm()

    korean_brand = PhoneBrand.objects.filter(
        name__iexact="Korea"
    )

    manufacturing_country_nationality = Phone.objects.filter(
        manufacturing_country__iexact=models.F("phone_name__brand__nationality")
    )

    context = {
        'form': form,
        "korean_brand": korean_brand,
        "phones": phones,
        "manufacturing_country_nationality": manufacturing_country_nationality
    }
    return render(request, "report.html", context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <div class="m-4">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Phone Registrations
{% endblock %}

{% block content %}
    <h1 class="mt-2 text-4xl font-bold mb-8">Phone Registration</h1>
    <h2 class="text-2xl font-bold mb-4">End Points</h2>
    <ul>
        <li><a href="{% url 'phone:index' %}">Home</a></li>
        <li><a href="http://localhost:8000/admin/">Admin Panel</a></li>
        <li><a href="{% url 'phone:phone-list' %}">Phones List</a></li>
        <li><a href="{% url 'phone:add-phone' %}">Add Phone</a></li>
        <li><a href="{% url 'phone:get-report' %}">Get Report</a></li>
    </ul>
{% endblock %}

templates/phone/add.html
{% extends 'base.html' %}

{% load tailwind_filters %}

{% block title %}
    Add Book
{% endblock %}

{% block content %}
    <div class="w-full max-w-2xl mx-auto sm:px-6 lg:px-8">
        <h1 class="text-4xl font-bold mb-8">Add a new phone</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
        <button type="submit" class="mt-2 text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">
            Save
        </button>
        </form>
    </div>
{% endblock %}

templates/phone/list.html
{% extends 'base.html' %}

{% block title %}
    Phone List
{% endblock %}

{% block content %}

    <h1 class="text-4xl font-bold mb-8">Phone List</h1>
    <ul>
        {% for phone in phones %}
            <li>{{ phone.phone_name }} - {{ phone.price }} - {{ phone.color }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/report.html
{% extends 'base.html' %}
{% load tailwind_filters %}

    {% block title %}
        Report of the phone registration
    {% endblock %}
{% block content %}
    <h2 class="text-2xl font-bold mb-4">All phone brands that their brand is Korea</h2>
    {% if korean_brand %}
    	{% for item in korean_brand %}
            {{ item.phone_name }} - {{ item.phone_price }}
    	{% endfor %}
    {% else %}
        <p>nothing</p>
    {% endif %}

    <hr>
    
    <div class="mt-2 w-full max-w-2xl mx-auto sm:px-6 lg:px-8">
    <h2 class="text-2xl font-bold mb-4">Search for Phones by Brand</h2>
    <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="mt-2 text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">
            Search
        </button>
    </form>
    {% if phones %}
        <ul>
        {% if phones %}
            {% for item in phones %}
                <li>
                    {{ item.phone_name }} - ${{ item.price }} - {{ item.color }} - {{ item.screen_size }} - {{ item.is_available }} - {{ item.manufacturing_country }}
                </li>
            {% endfor %}
        {% else %}
            <li>No phones found for brand "{{ brand }}"</li>
        {% endif %}
    </ul>
    <a href="{% url 'phone:get-report' %}">Search again</a>
    {% endif %}
    
    </div>

    <hr>

    <h2 class="text-2xl font-bold mb-4">Phones that their manufacturing country is equal to their nationality</h2>
    {% if manufacturing_country_nationality %}
        {% for item in manufacturing_country_nationality %}
            <li>
                {{ item.phone_name }} - ${{ item.price }} - {{ item.color }} - {{ item.screen_size }} - {{ item.is_available }} - {{ item.manufacturing_country }}
            </li>
        {% endfor %}
    {% endif %}

    <hr>
{% endblock %}